### ISSUE TITLE
unable to clone repo

### ISSUE THREAD

**Issue by andreashandel** [okichris90/Okitondo-Cavros-Repository#1]
i just tried to clone this repo but wasn't able to. i think the problem is that you have special characters in a file, there is one called "Figure 1: Age & flu uptake distribution.png". I think the "&" sign, and maybe also the ":" sign lead to the failure. Can you check all your file names and make sure they don't contain special characters/symbols. Once fixed, let me know and I'll try to clone again.

**Comment by okichris90** [comment]
I just renamed the files to exclude any special characters. Please check and let us know.

**Comment by andreashandel** [comment]
looks like it worked now. thanks.
